# Site settings
title: 'lil bits'
email: notryan@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Ryan Blechers blog. Each post covers short things I have learned
  in the fields of software and electrical engineering. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://notryan.github.com" # the base hostname & protocol for your site
twitter_username: Options_r
github_username:  notryanb

# Build settings
markdown: kramdown
